/**
 * Tests for the domain↔wire mapping seam (S21).
 *
 * These tests do double duty:
 *   1. RUNTIME — assert toWireOp / fromWirePulledRow carry the right field
 *      values in both directions.
 *   2. TYPE-LEVEL DRIFT GUARD — they import the GENERATED wire `Op`/`PulledRow`
 *      types (from `@bowli/shared`, generated by tygo from the Go sync structs)
 *      and assert the mapper outputs satisfy them. If the Go structs / json tags
 *      ever change, the generated types change, and this file stops compiling —
 *      so Go↔TS drift fails `pnpm typecheck`, not silently at runtime.
 */

import { describe, expect, it } from 'vitest';

import type { Op, PulledRow as WirePulledRow } from '@bowli/shared';

import type { PulledRow, SyncOpPayload } from './drain';
import type { RemoteRow } from './reconcile';
import { fromWirePulledRow, toWireOp } from './wireMap';

describe('toWireOp', () => {
  it('maps a local upsert op to the wire Op, field-for-field', () => {
    const local: SyncOpPayload = {
      id: '0190aa00-0000-7000-8000-000000000001', // local-only outbox PK
      entityTable: 'players',
      entityId: '0190bb00-0000-7000-8000-000000000002',
      op: 'upsert',
      payload: {
        id: '0190bb00-0000-7000-8000-000000000002',
        name: 'Mike',
        isSelf: false,
        updatedAt: 1718668800000,
        deletedAt: null,
      },
      entityUpdatedAt: 1718668800000,
    };

    const wire: Op = toWireOp(local);

    expect(wire).toStrictEqual({
      entityTable: 'players',
      entityId: '0190bb00-0000-7000-8000-000000000002',
      op: 'upsert',
      payload: {
        id: '0190bb00-0000-7000-8000-000000000002',
        name: 'Mike',
        isSelf: false,
        updatedAt: 1718668800000,
        deletedAt: null,
      },
      entityUpdatedAt: 1718668800000,
    });
  });

  it('drops the local-only outbox id (not part of the wire Op)', () => {
    const local: SyncOpPayload = {
      id: 'local-outbox-pk',
      entityTable: 'games',
      entityId: 'game-1',
      op: 'upsert',
      payload: { id: 'game-1' },
      entityUpdatedAt: 42,
    };

    const wire = toWireOp(local);

    expect('id' in wire).toBe(false);
    expect(Object.keys(wire).sort()).toStrictEqual([
      'entityId',
      'entityTable',
      'entityUpdatedAt',
      'op',
      'payload',
    ]);
  });

  it('maps a delete op, carrying the minimal { id } payload marker', () => {
    const local: SyncOpPayload = {
      id: 'op-2',
      entityTable: 'frames',
      entityId: 'frame-9',
      op: 'delete',
      payload: { id: 'frame-9' },
      entityUpdatedAt: 1718668800001,
    };

    const wire = toWireOp(local);

    expect(wire.op).toBe('delete');
    expect(wire.payload).toStrictEqual({ id: 'frame-9' });
    expect(wire.entityUpdatedAt).toBe(1718668800001);
  });

  it('normalizes a null/undefined/non-object payload to {} (wire requires an object)', () => {
    const base = {
      id: 'op-3',
      entityTable: 'sessions',
      entityId: 's-1',
      op: 'delete',
      entityUpdatedAt: 7,
    } as const;

    expect(toWireOp({ ...base, payload: null }).payload).toStrictEqual({});
    expect(toWireOp({ ...base, payload: undefined }).payload).toStrictEqual({});
    // Arrays are not valid wire payloads (map[string]unknown) — normalize too.
    expect(toWireOp({ ...base, payload: [1, 2, 3] }).payload).toStrictEqual({});
    expect(toWireOp({ ...base, payload: 'oops' }).payload).toStrictEqual({});
  });

  it('round-trips the addressing fields through the wire shape', () => {
    const local: SyncOpPayload = {
      id: 'op-rt',
      entityTable: 'locations',
      entityId: 'loc-7',
      op: 'upsert',
      payload: { id: 'loc-7', name: 'Sunset Lanes' },
      entityUpdatedAt: 999,
    };

    const wire = toWireOp(local);

    // Reconstruct the wire-relevant slice of the local op from the wire Op and
    // assert equality — the seam is loss-free for everything but the local PK.
    const reconstructed = {
      entityTable: wire.entityTable,
      entityId: wire.entityId,
      op: wire.op,
      payload: wire.payload,
      entityUpdatedAt: wire.entityUpdatedAt,
    };
    expect(reconstructed).toStrictEqual({
      entityTable: local.entityTable,
      entityId: local.entityId,
      op: local.op,
      payload: local.payload,
      entityUpdatedAt: local.entityUpdatedAt,
    });
  });
});

describe('fromWirePulledRow', () => {
  it('maps a pulled wire row into the shape applyRemoteRows consumes', () => {
    const wire: WirePulledRow = {
      entityTable: 'players',
      row: {
        id: '0190cc00-0000-7000-8000-000000000003',
        name: 'Nancy',
        isSelf: false,
        updatedAt: 1718668800500,
        deletedAt: null,
      },
    };

    const pulled: PulledRow = fromWirePulledRow(wire);

    expect(pulled.entityTable).toBe('players');
    // The row carries the three sync fields applyRemoteRows / reconcile need.
    const r: RemoteRow = pulled.row;
    expect(r.id).toBe('0190cc00-0000-7000-8000-000000000003');
    expect(r.updatedAt).toBe(1718668800500);
    expect(r.deletedAt).toBeNull();
    // Entity columns pass straight through.
    expect(r.name).toBe('Nancy');
  });

  it('carries a tombstone (deletedAt set) through unchanged', () => {
    const wire: WirePulledRow = {
      entityTable: 'games',
      row: {
        id: 'g-1',
        updatedAt: 1718668800600,
        deletedAt: 1718668800600,
      },
    };

    const pulled = fromWirePulledRow(wire);

    expect(pulled.row.deletedAt).toBe(1718668800600);
    expect(pulled.entityTable).toBe('games');
  });
});
