/**
 * Domain↔wire mapping seam (S21).
 *
 * Go is the source of truth for the sync WIRE types (`@bowli/shared` →
 * `packages/shared/generated/wire.ts`, generated by tygo from
 * services/api/internal/domain/sync.go). The device speaks its OWN local op
 * vocabulary — the `sync_ops` outbox row ({@link SyncOpPayload}) on the push
 * side, and the pulled-row shape {@link applyRemoteRows} consumes on the pull
 * side. This module is the ONE place those two vocabularies meet.
 *
 * Why a seam at all when the shapes line up today: typing the mapping AGAINST
 * the generated wire types means any future change to the Go structs (a renamed
 * json tag, a new required field) surfaces as a COMPILE error here — one spot —
 * instead of silently mis-serializing at runtime. The functions are near-
 * identity now, written out explicitly so that guarantee holds.
 *
 * Pure: no `expo-sqlite`, no `any`. Node-testable like the rest of `sync/`.
 */

import type { Op, PulledRow as WirePulledRow } from '@bowli/shared';

import type { PulledRow, SyncOpPayload } from './drain';
import type { RemoteRow } from './reconcile';

/**
 * The wire `Op` requires `payload` to be a JSON object (`map[string]unknown` in
 * Go). The local op carries `payload: unknown` — for an 'upsert' it's the full
 * row snapshot (an object), for a 'delete' a minimal `{ id }` marker. This
 * narrows that `unknown` to the wire's record shape, normalizing `null`/
 * `undefined` to an empty object so the wire field is never absent.
 */
function toPayloadRecord(payload: unknown): { [key: string]: unknown } {
  if (typeof payload === 'object' && payload !== null && !Array.isArray(payload)) {
    return payload as { [key: string]: unknown };
  }
  return {};
}

/**
 * Map a local outbox op (the wire-bound projection a drain hands the transport)
 * to the wire {@link Op} the Go `POST /sync/push` accepts.
 *
 * Field alignment with the Go json tags (sync.go `Op`):
 *   local.entityTable     → Op.entityTable      (`json:"entityTable"`)
 *   local.entityId        → Op.entityId         (`json:"entityId"`)
 *   local.op              → Op.op               (`json:"op"`, OpKind)
 *   local.payload         → Op.payload          (`json:"payload"`)
 *   local.entityUpdatedAt → Op.entityUpdatedAt  (`json:"entityUpdatedAt"`)
 *
 * The local-only `id` (the outbox PK / idempotency key) is intentionally NOT on
 * the wire `Op` — the server keys LWW on the entity row, not the op.
 */
export function toWireOp(localOp: SyncOpPayload): Op {
  return {
    entityTable: localOp.entityTable,
    entityId: localOp.entityId,
    // local `'upsert' | 'delete'` is assignable to the wire OpKind (string).
    op: localOp.op,
    payload: toPayloadRecord(localOp.payload),
    entityUpdatedAt: localOp.entityUpdatedAt,
  };
}

/**
 * Map a pulled wire {@link WirePulledRow} (`GET /sync/pull` → sync.go
 * `PulledRow`) into the table-tagged {@link PulledRow} that `drainPull` groups
 * and {@link applyRemoteRows} (S18) consumes.
 *
 * Field alignment with the Go json tags (sync.go `PulledRow`):
 *   PulledRow.entityTable → entityTable (`json:"entityTable"`)
 *   PulledRow.row         → row         (`json:"row"`)
 *
 * The wire `row` is `{ [key: string]: unknown }`; reconcile's {@link RemoteRow}
 * is `SyncableRow & { [column: string]: unknown }` — i.e. it ALSO requires the
 * three sync fields (`id`, `updatedAt`, `deletedAt`). The server only ever pulls
 * full syncable rows, so the cast asserts that invariant at this seam; the
 * structural index signature matches, so this is a widening of guarantees, not
 * a reshape.
 */
export function fromWirePulledRow(row: WirePulledRow): PulledRow {
  return {
    entityTable: row.entityTable,
    row: row.row as RemoteRow,
  };
}
